stages:
  data_ingestion:
    cmd: python3 src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw

  data_preprocessing:
    cmd: python3 src/features/data_preprocessing.py
    deps:
    - src/features/data_preprocessing.py
    - data/raw/train.csv
    - data/raw/test.csv
    outs:
    - data/interim

  model_building:
    cmd: python3 src/model/model_building.py
    deps:
      - src/model/model_building.py
      - data/interim/train_processed.csv
      - data/interim/test_processed.csv
      - params.yaml
    params:
      - model_building.ngram_range
      - model_building.max_features
      - model_building.learning_rate
      - model_building.max_depth
      - model_building.n_estimators
    outs:
      - models/model
      - models/vectorizers

  model_evaluation:
    cmd: PYTHONPATH=. python3 src/visualization/model_evaluation.py
    # cmd: python3 src/visualization/model_evaluation.py
    deps:
    - src/visualization/model_evaluation.py
    - data/interim/test_processed.csv
    - models
    metrics:
    - reports/metrics/metrics.json:
        cache: false
    outs:
    - reports/experiment_info.json

  model_registration:
    cmd: PYTHONPATH=. python3 src/visualization/model_registration.py
    deps:
    - src/visualization/model_registration.py
    - reports/experiment_info.json

